### ISSUE TITLE
Open sourcing checklist

### ISSUE THREAD

**Issue by Narnach** [q-m/questionmark-barcodes#3]
We have discovered that private gems are hard to work with from a permissions perspective across Github repositories. The code in this repository is not super secret, so we're opening it up to the public. We will _not_ publish a gem, because we don't see this code as something that is useful in a generic way that others can build dependencies upon.

This means we need to do a few things to make this possible:

- [x] #7
  - [x] Update readme/documentation with more context + instructions
- [x] Transfer some of our internal ideas here in the form of new issues, setting a roadmap for ourselves
- [x] #5
- [x] Protect our `main` branch by mandating CI passes before merge (@wvengen should have permission to set this up)
- [x] #4
- [x] #14

Things can be checked off the list, or we can convert some to issues themselves if they become PRs or need more of their own context / decisions.
